"""empty message

Revision ID: 11caedebde14
Revises: 79be3adc7cc0
Create Date: 2020-04-15 20:53:56.014817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11caedebde14'
down_revision = '79be3adc7cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'timeStamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('timeStamp', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
