"""empty message

Revision ID: c52fbb83c70a
Revises: 6a4910ea4d19
Create Date: 2020-04-16 01:41:41.241001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52fbb83c70a'
down_revision = '6a4910ea4d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'timestamp')
    # ### end Alembic commands ###
